name = "roll-doradocasino-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradocasino.pl"
HMAC_KEY = "317b282dfd958ea825af689d7ec9f2791fae94922e3e1ba5b411345363fddbcb"
COOKIE_NAME = "euk"
PLAY_PATH = "start-now"
BUTTON_ID = "p4546a2e995b9dd4af805ea1cd92a130a"
GATE_SALT = "3628378671d460a5"
