name = "roll-doradocasino-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradocasino.pl"
HMAC_KEY = "317b282dfd958ea825af689d7ec9f2791fae94922e3e1ba5b411345363fddbcb"
COOKIE_NAME = "udf"
PLAY_PATH = "launch"
BUTTON_ID = "p4546a2e995b9dd4af805ea1cd92a130a"
GATE_SALT = "439bfb4ddbafe531"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "oj7p"
CTA_SELECTOR = ".play-button"
